// <auto-generated />
namespace TMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newMigrateToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newMigrateToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202504020744263_newMigrateToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
